apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
#       imagePullSecrets:
# {{- range .Values.backend.imagePullSecrets }}
#         - name: {{ . }}
# {{- end }}

      containers:
        - name: backend
          imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"

          ports:
            - containerPort: {{ .Values.backend.containerPort }}

          resources:
            requests:
              cpu: {{ .Values.backend.requests.cpu }}
              memory: {{ .Values.backend.requests.memory }}
            limits:
              cpu: {{ .Values.backend.limits.cpu }}
              memory: {{ .Values.backend.limits.memory }}

          env:
{{- toYaml .Values.backend.env | nindent 12 }}
{{/* 
        #   {{- range .Values.backend.env }}
        #   - name: {{ .name }}
        #     valueFrom:
        #       configMapKeyRef:
        #         name: {{ .valueFrom.configMapKeyRef.name }}
        #         key: {{ .valueFrom.configMapKeyRef.key }}
        #   {{- end }}
*/}}
---

# service

apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: {{ .Values.backend.serviceType }}

  selector:
    app: backend

  ports:
    - port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.containerPort }}
      nodePort: {{ .Values.backend.nodePort }}