apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: {{ .Values.database.replicaCount }}

  selector:
    matchLabels:
      app: database

  template:
    metadata:
      labels:
        app: database

    spec:
#       imagePullSecrets:
# {{- range .Values.database.imagePullSecrets }}
#         - name: {{ . }}
# {{- end }}

      containers:
        - name: database
          imagePullPolicy: {{ .Values.database.imagePullPolicy }}
          image: "{{ .Values.database.image }}:{{ .Values.database.tag }}"

          ports:
            - containerPort: {{ .Values.database.containerPort }}

          resources:
            requests:
              cpu: {{ .Values.database.requests.cpu }}
              memory: {{ .Values.database.requests.memory }}
            limits:
              cpu: {{ .Values.database.limits.cpu }}
              memory: {{ .Values.database.limits.memory }}

          env:
{{- toYaml .Values.database.env | nindent 12 }}

{{/*
        #   {{- range .Values.database.env }}
        #   - name: {{ .name }}
        #     valueFrom:
        #       configMapKeyRef:
        #         name: {{ .valueFrom.configMapKeyRef.name }}
        #         key: {{ .valueFrom.configMapKeyRef.key }}
        #   {{- end }}
        */}}

---

# service

apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  type: {{ .Values.database.serviceType }}

  selector:
    app: database

  ports:
    - port: {{ .Values.database.servicePort }}
      targetPort: {{ .Values.database.containerPort }}
      nodePort: {{ .Values.database.nodePort }}