# kubectl apply --server-side -f https://raw.githubusercontent.com/external-secrets/external-secrets/main/deploy/crds/bundle.yaml


# Ref:- https://external-secrets.io/latest/provider/azure-key-vault/#creating-external-secret
# Create Kubernetes Secret for Azure Authentication
apiVersion: v1
kind: Secret
metadata:
  name: kuber-secret
  namespace: default
type: Opaque
stringData:
  clientId: e73fb9ed-e8dc-41bb-ba58-17ac522ba68e
  clientSecret: _iA8Q~xx5fRt07b0q602kAjiEi0TLKSv2jb4ZbeQ

---
# Create SecretStore (Connect Kubernetes → Key Vault)

# apiVersion: external-secrets.io/v1
apiVersion: external-secrets.io/v1beta1  # Change this from v1 to v1beta1
kind: SecretStore
metadata:
  name: azure-store
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      tenantId: 637b234b-6c6b-44fc-8606-5af9e7f38949
      vaultUrl: "https://kubervaults01.vault.azure.net/"
      authSecretRef:
        clientId:
          name: kuber-secret
          key: clientId
        clientSecret:
          name: kuber-secret
          key: clientSecret


---

# Create ExternalSecret (Pull Data from Key Vault)

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-store
    kind: SecretStore
  target:
    name: backend-secret
    creationPolicy: Owner

  data:
    - secretKey: MONGO
      remoteRef:
        key: MONGO

    - secretKey: DB
      remoteRef:
        key: DB

    - secretKey: collection
      remoteRef:
        key: collection

    - secretKey: PORT
      remoteRef:
        key: PORT