# configmap

apiVersion: v1
kind: ConfigMap
metadata:
  name: kuber-config
  namespace: default
data:
  DB_NAME: "stu_db"
  COLLECTION_NAME: "students"
  PORT: "5000"
  # VITE_BACKEND_URL: http://backend-service:5000
  VITE_BACKEND_URL: "/api"


---

# secret

apiVersion: v1
kind: Secret
metadata:
  name: kuber-secret
  namespace: default
data:
  MONGO_URI: "bW9uZ29kYitzcnY6Ly9zaGFybWF2aXNoYWwwMDkxMV9kYl91c2VyOmRFRDdIc3k1V1pHV1lXaWlAc3R1ZGVudC5oaTE1dmJoLm1vbmdvZGIubmV0L3N0dV9kYg=="
