apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dep
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name : dockerhub-secret
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: env
                    operator: In
                    values:
                      - sbe
      containers:
        - name: frontend
          image: sharmarjit1986/sfe:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 4173
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 4173
          #   initialDelaySeconds: 20
          #   periodSeconds: 10

          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 4173
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          resources:
            requests:
              cpu: "400m"
              memory: "400Mi"
            limits:
              memory: "500Mi"
              cpu: "500m"

          env:
          - name: VITE_BACKEND_URL
            valueFrom: 
              configMapKeyRef:
                name: kuber-config
                key: VITE_BACKEND_URL